@startuml
'https://plantuml.com/sequence-diagram

LoginPage -> SubscriptionViewModel: purchaseSubscription()


activate SubscriptionViewModel
SubscriptionViewModel -> SubscriptionRepository: purchaseSubscription()
activate SubscriptionRepository
SubscriptionRepository -> BillingClientManager: purchaseSubscription()
deactivate SubscriptionRepository
activate BillingClientManager
BillingClientManager -> BillingClientManager: launchBillingFlow()
deactivate BillingClientManager

BillingClientManager --> BillingClientManager: onPurchasesUpdated()
activate BillingClientManager
BillingClientManager -->  SubscriptionViewModel: observe Purchases
deactivate SubscriptionRepository
BillingClientManager --> BillingClientManager: acknowledgePurchase()
deactivate BillingClientManager

alt responseCode == OK

    SubscriptionViewModel -> IEntitlementManager: saveCredentials()
    activate SubscriptionViewModel
    activate IEntitlementManager
    SubscriptionViewModel --> LoginPage: navigate to upload page
    deactivate IEntitlementManager
    deactivate SubscriptionViewModel
end


@enduml