@startuml
'https://plantuml.com/sequence-diagram
UploadNumberPage -> SubscriptionViewModel: onCreate()

'initiate billing client connection
SubscriptionViewModel ->  SubscriptionRepository: init()
SubscriptionRepository -> BillingClientManager: startConnection()

activate BillingClientManager
BillingClientManager --> SubscriptionViewModel: callback connection status


'query purchase and product details
activate BillingClientManager
BillingClientManager -> BillingClientManager: queryPurchase()

BillingClientManager -> BillingClientManager: queryProductDetails()

BillingClientManager --> SubscriptionViewModel: observe ProductDetails
deactivate BillingClientManager



' user can purchase subscription only if product details is not null and connection is established
alt product details != null
    SubscriptionViewModel --> UploadNumberPage: enable purchase button
    UploadNumberPage -> SubscriptionViewModel: purchaseSubscription()


activate SubscriptionViewModel
SubscriptionViewModel -> SubscriptionRepository: purchaseSubscription()
activate SubscriptionRepository
SubscriptionRepository -> BillingClientManager: purchaseSubscription()
deactivate SubscriptionRepository
activate BillingClientManager
BillingClientManager -> BillingClientManager: launchBillingFlow()
deactivate BillingClientManager

BillingClientManager --> BillingClientManager: onPurchasesUpdated()
activate BillingClientManager
BillingClientManager -->  SubscriptionViewModel: observe Purchases
deactivate SubscriptionRepository
BillingClientManager --> BillingClientManager: acknowledgePurchase()
deactivate BillingClientManager

alt responseCode == OK
    activate SubscriptionViewModel
    SubscriptionViewModel -> IEntitlementManager: saveCredentials()
    activate IEntitlementManager
    SubscriptionViewModel -> IEntitlementManager: enablePremiumFeatures()
    deactivate IEntitlementManager
    deactivate SubscriptionViewModel
end
end

@enduml