@startuml
'https://plantuml.com/sequence-diagram


LoginPage -> SubscriptionViewModel: onCreate()

'initiate billing client connection
SubscriptionViewModel ->  SubscriptionRepository: init()
SubscriptionRepository -> BillingClientManager: startConnection()

activate BillingClientManager
BillingClientManager --> SubscriptionViewModel: callback connection status


'query purchase and product details

BillingClientManager -> BillingClientManager: queryPurchase()
activate BillingClientManager
BillingClientManager --> SubscriptionViewModel: observe purchases

alt purchases is empty
    BillingClientManager -> BillingClientManager: queryProductDetails()
    deactivate BillingClientManager
    BillingClientManager --> SubscriptionViewModel: observe ProductDetails
    activate SubscriptionViewModel
    SubscriptionViewModel --> LoginPage: observe product price
    deactivate SubscriptionViewModel
    activate LoginPage

    LoginPage --> LoginPage: enable purchase button
    deactivate LoginPage


else
    SubscriptionViewModel -> IEntitlementManager: saveCredentials()
    activate SubscriptionViewModel
    SubscriptionViewModel --> LoginPage: navigate to upload page
    deactivate SubscriptionViewModel
deactivate BillingClientManager
end



@enduml